import "./globals.css";

export const metadata = {
  title: "luxury-hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">

      <body className="font-f_3">
        {children}
      </body>

    </html>
  );
}
